export const GET_ALL_DOGS = 'GET_ALL_DOGS';
export const GET_ALL_TEMPERAMENTS = 'GET_ALL_TEMPERAMENTS';
export const API_OR_DB_FILTER = 'API_OR_DB_FILTER';
export const GET_DOGS_BY_NAME = 'GET_DOGS_BY_NAME';
export const GET_DOG_BY_ID = 'GET_DOG_BY_ID';
export const ALPHABETIC_SORT = 'ALPHABETIC_SORT';
export const WEIGHT_SORT = 'WEIGHT_SORT';
export const TEMPERAMENT_FILTER = 'TEMPERAMENT_FILTER';